api/urls.py
from django.urls import path,include
from .views import PostApiViewSet,CategoryList,CategoryPostList
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'posts', PostApiViewSet, basename='posts')

urlpatterns = [
	path(
		"posts/by-time/<str:period_name>/",
		PostApiViewSet.as_view({"get": "list"}),
		name="posts-by-time",
		),
	path("categories/", CategoryList.as_view(),name='api_category_list'),
	path("categories/<int:pk>", CategoryPostList.as_view(),name='api_category_post_list'),

	path("auth/", include("rest_framework.urls")),

	#JWT
	path("jwt/", TokenObtainPairView.as_view(),name="jwt_obtain_pair"),
	path("jwt/refresh/", TokenRefreshView.as_view(),name="jwt_refresh"),
]

urlpatterns+=router.urls

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/v1/", include("api.urls")),
    path('accounts/',include('account.urls')),
    path('comment/', include('comment.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path("",include('blog.urls')),

]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.contenttypes.fields import GenericRelation
from django.urls import reverse
from comment.models import Comment
from ckeditor.fields import RichTextField

class Category(models.Model):
	parent=models.ForeignKey('self',default=None,null=True,blank=True,on_delete=models.SET_NULL,related_name='children')
	title=models.CharField(max_length=200)
	slug=models.SlugField(max_length=200,unique=True)
	status=models.BooleanField(default=True)

	class Meta:
		verbose_name_plural='Categories'
		ordering=['parent__id']
	def __str__(self):
		return self.title
	def get_absolute_url(self):
		return reverse('post_detail_url', kwargs={'slug': self.slug})

class Post(models.Model):
	STATUS_CHOICE=[
		('d','Draft'),
		('p','Publish'),
		('r','Rejected'),
		('s','Send to Manager')

	]

	title=models.CharField(max_length=200)
	slug=models.SlugField(max_length=200,unique=True)
	author=models.ForeignKey(settings.AUTH_USER_MODEL,null=True,on_delete=models.SET_NULL,related_name='articles')
	category=models.ManyToManyField(Category,related_name='articles')
	description=RichTextField()
	thumbnail=models .ImageField(upload_to='article-image',null=True)
	published=models.DateTimeField(default=timezone.now)
	created=models.DateTimeField(auto_now_add=True)
	updated=models.DateTimeField(auto_now=True)
	status=models.CharField(max_length=1,choices=STATUS_CHOICE)
	comments = GenericRelation(Comment)
	hits=models.ManyToManyField('IpAddress',through='Hit')

	def __str__(self):
		return self.title

	class Meta:
		ordering=['-published']


class IpAddress(models.Model):
	ip=models.GenericIPAddressField()


class Hit(models.Model):
	ip=models.ForeignKey(IpAddress,on_delete=models.CASCADE)
	post=models.ForeignKey(Post,on_delete=models.CASCADE)
	created=models.DateTimeField(auto_now_add=True)

	class Meta:
		unique_together=['ip','post']


class AboutCategory(models.Model):
	title=models.CharField(max_length=200)
	description=models.TextField(blank=True)
	def __str__(self):
		return self.title
class About(models.Model):
	about_category=models.ForeignKey(AboutCategory,on_delete=models.SET_NULL,null=True)
	description=models.TextField(blank=True)

templates/about/about.html
{%extends 'blog/base_blog.html'%}
{%block content%}
<div class="container">
<div class="row justify-content-center">
    <div class="col-12 col-lg-10 col-xl-8 mx-auto">
        <h2 class="h3 mb-4 page-title">About This Blog</h2>
        <div class="my-4">

            <hr class="my-4" />
            {%for object in object_list%}
            <strong class="mb-0">{{object.title}}</strong>
            <p></p>
            <div class="list-group mb-5 shadow">
            	{%for sub in object.about_set.all%}
                <div class="list-group-item">
                    <div class="row align-items-center">
                        <div class="col">
                            
                            <p class="text-muted mb-0">{{sub.description}}</p>
                        </div>

                    </div>
                </div>
                {%endfor%}
            </div>
            <hr class="my-4" />
            {%endfor%}

        </div>
    </div>
</div>

</div>
{%endblock%}