api/urls.py
from django.urls import path,include
from .views import PostApiViewSet,CategoryList,CategoryPostList
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'posts', PostApiViewSet, basename='posts')

urlpatterns = [
	path(
		"posts/by-time/<str:period_name>/",
		PostApiViewSet.as_view({"get": "list"}),
		name="posts-by-time",
		),
	path("categories/", CategoryList.as_view(),name='api_category_list'),
	path("categories/<int:pk>", CategoryPostList.as_view(),name='api_category_post_list'),

	path("auth/", include("rest_framework.urls")),

	#JWT
	path("jwt/", TokenObtainPairView.as_view(),name="jwt_obtain_pair"),
	path("jwt/refresh/", TokenRefreshView.as_view(),name="jwt_refresh"),
]

urlpatterns+=router.urls

blog/urls.py
from django.urls import path
from . import views


app_name='blog'
urlpatterns=[
	path('',views.Index.as_view(),name='index'),
	path('post/<str:slug>/',views.PostDetailView.as_view(),name='post_detail'),
	path('category/<slug:cat>/',views.CategoryPostList.as_view(),name='category_post_list'),
	path('search/',views.Search.as_view(),name='search_result'),
	path('contact/',views.ContactMe.as_view(),name='contact_me'),
	path('about/',views.About.as_view(),name='about')


]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/v1/", include("api.urls")),
    path('accounts/',include('account.urls')),
    path('comment/', include('comment.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path("",include('blog.urls')),

]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/_most_viewed_posts.html
  <h2>
    Most Viewed Posts:
  </h2>
  {%for post in posts%}
  <div class="col m-2">
    <div class="card">

      <div class="card-body">
        <a href="{% url 'blog:post_detail' post.slug%}">
        <h5 class="card-title">{{post.title}}</h5>
              </a>
        <p class="card-text">{{post.description|safe|truncatewords:20}}</p>
      </div>

    </div>
  </div>
  {%endfor%}

templates/partials/_navbar.html
    <div class="bg-body-tertiary container-fluid ">
      <div class="text-start">
            <a class='text-decoration-none fs-2 text-black' href="{%url 'blog:index'%}">Mansouri Blog</a>

      </div>

  </div>
  <nav class="navbar navbar-expand-lg bg-body-tertiary" style="margin-bottom:30px">
   <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">


{%if request.user.is_authenticated%}
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Account
          </a>
          <ul class="dropdown-menu">

            <li><a class="dropdown-item" href="{%url 'author-posts' request.user.pk %}">Profile</a></li>
            <li><a class="dropdown-item" href="{%url 'logout'%}">Logout</a></li>


          </ul>
        </li>

{%else%}
        <li class="nav-item">
          <a class="nav-link text-black" href="{%url 'login'%}">Login</a>
        </li>

{%endif%}


         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            category
          </a>
          <ul class="dropdown-menu">
            {%for cat in category%}
            <li><a class="dropdown-item" href="{%url 'blog:category_post_list' cat.slug%}">{{cat.title}}</a></li>
            {%endfor%}

          </ul>
        </li>

        <li class="nav-item">
          <a class="nav-link  {%if 'contact' in request.path%}shadow{%endif%}" href="{% url 'blog:contact_me'%}">Contact Me</a>
        </li>
        <li class="nav-item">
          <a class="nav-link  {%if 'about' in request.path%}shadow{%endif%}" href="{% url 'blog:about'%}">About</a>
        </li>


      </ul>
      <form class="d-flex"  method='GET' action="{%url 'blog:search_result'%}" >
        <input class="form-control me-2" type="text" placeholder="Search" name='search' aria-label="Search">
        <button class="btn btn-outline-success" type="submit" >Search</button>
      </form>

      
    </div>
  </div>
</nav>

templates/partials/_pagination.html
{%load blog_tags%}	

{% with page_obj.paginator.num_pages as num_pages and page_obj.number as number%}
{%if num_pages > 1%}

	    <!-- pagination -->
		<nav aria-label="Page navigation example">
		  <ul class="pagination">
		    <li class="page-item">
		    	{%if page_obj.has_previous%}
		      <a class="page-link" href="{{request.path}}?page={{page_obj.previous_page_number}}" aria-label="Previous">
		        <span aria-hidden="true">&laquo;</span>
		      </a>
		      {%else%}
				<a class="page-link disabled" href="" aria-label="Previous">
			        <span aria-hidden="true">&laquo;</span>
			      </a>
		      {%endif%} 
		    </li>




		    <!-- first page -->
		    <li class="page-item {% active_page 1%}"><a class="page-link" href="{{request.path}}?page=1">1</a></li>
		    <!-- if total pages number less than 5 -->

		    		{% create_page_link "" %}
		    	    		
		    	




			<!-- last page number -->
		    <li class="page-item"><a class="page-link {% active_page num_pages %}" href="{{request.path}}?page={{num_pages}}">{{num_pages}}</a></li>



		    <!-- next page -->
		    <li class="page-item">
		    	{%if page_obj.has_next%}
		      <a class="page-link" href="{{request.path}}?page={{page_obj.next_page_number}}" aria-label="Next">
		        <span aria-hidden="true">&raquo;</span>
		      </a>
		      {%else%}
		      <a class="page-link disabled" href="" aria-label="Next">
		        <span aria-hidden="true">&raquo;</span>
		      </a>
		      {%endif%}
		    </li>
		  </ul>
		</nav>

{%endif%}
{%endwith%}

templates/partials/_profile_navbar.html
  {%load static%}

    <div class="bg-body-tertiary container-fluid ">
      <div class="text-start">
            <a class='text-decoration-none fs-2 text-black' href="{%url 'blog:index'%}">Mansouri Blog</a>

      </div>

  </div>

  <nav class="navbar navbar-expand-lg bg-body-tertiary" style="margin-bottom:30px">
   <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">


         
          <ul class="dropdown-menu">

            <li><a class="dropdown-item" href="{%url 'profile' request.user.pk %}">Profile</a></li>
            <li><a class="dropdown-item" href="{%url 'logout'%}">Logout</a></li>


          </ul>
        </li>
{%if request.user.is_author or request.user.is_superuser%}
        <li class="nav-item ">
          <a class="nav-link text-black {%if 'posts' in request.path%}shadow{%endif%}" 
          href="{%url 'author-posts' request.user.pk%}">Posts</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link text-black {%if 'create-post' in request.path%}shadow{%endif%}" 
          href="{%url 'create-post'%}">Create Posts</a>
        </li>
{%endif%}


      </ul>
        <div class="dropdown">
      <a href="#" class="d-flex align-items-center link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
        <img 
         {%if request.user.profile_image%}
        src="{{request.user.profile_image.url}}" 
        {%else%}
        src="{%static 'img/profile_image/blank-profile.png'%}" 
        {%endif%}
         alt="{{request.user.username}}" 
         class="rounded-circle me-2"
          width="32" height="32">
        <strong>{{request.user.username}}</strong>
      </a>
      <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
        <li><a class="dropdown-item" href="{%url 'profile' request.user.pk %}">Profile</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="{%url 'logout' %}">Sign out</a></li>
      </ul>
    </div>
      
    </div>
  </div>
</nav>

templates/partials/_status_tag.html
{%if status == 'p' %}
			        
<span class="badge text-bg-success">publish</span>

{%elif status == 'd' %}
<span class="badge text-bg-secondary">draft</span>
{%elif status == 'r' %}
<span class="badge text-bg-danger">reject</span>
{%elif status == 's' %}
<span class="badge text-bg-info">sent to manager</span>
{%endif%}